# Generated by Django 4.2 on 2024-05-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inmueble_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarriendo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='Pendiente'),
        ),
    ]
